--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/NurAzliYT/EconomyS
build-by-default: true
branches:
- master
projects:
  EconomyAPI:
    path: EconomyAPI/
    model: virion
    type: library
  EconomyAirport:
    path: EconomyAirport/
  EconomyAuction:
    path: EconomyAuction/
  EconomyCasino:
    path: EconomyCasino/
  EconomyJob:
    path: EconomyJob/
  EconomyLand:
    path: EconomyLand/
  EconomyPShop:
    path: EconomyPShop/
  EconomyProperty:
    path: EconomyProperty/
  EconomySell:
    path: EconomySell/
  EconomyShop:
    path: EconomyShop/
  EconomyTax:
    path: EconomyTax/
  EconomyUsury:
    path: EconomyUsury/
...
